
version: "3.9"

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - mynet
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8090:80
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynet
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  mynet:
    name: mynet